### PR TITLE
Localheinz fix/bootstrapping

### PR DESCRIPTION
**Pull request by everton-rosario**
Solved the conflict and merged PR of @localheinz

### CODE REVIEW

**Comment by localheinz** [comment]
@everton-rosario 

I had resolved the conflict on https://github.com/facebook/facebook-instant-articles-sdk-php/pull/36 already, though. 😄

**Comment by everton-rosario** [comment]
We need to add composer.lock to .gitignore
Can you send a PR about it, @localheinz ?

**Comment by simonengelhardt** [comment]
I don't think we should gitignore composer.lock since that goes against the [recommendation from Composer](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file) and could potentially break our upcoming CI integration.

**Comment by localheinz** [comment]
@everton-rosario @simonengelhardt 

Personally, I would recommend to always check in `composer.lock` as it is a lot easier to reproduce issues, which otherwise could be caused by using different versions of dependencies.

However, major frameworks often don't check it in, for example

* https://github.com/symfony/symfony/blob/master/.gitignore#L2
* https://github.com/zendframework/zf2/blob/master/.gitignore#L12

How about checking in `composer.lock`, though, as it speeds up development, and then potentially running at least those builds:

* one that uses the lowest dependencies (`composer update --prefer-lowest`)
* one that uses locked dependencies (`composer install`)
* one that uses the highest dependencies (`composer update`)

For reference, see

* https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file
* https://getcomposer.org/doc/03-cli.md#update

**Pull request merged**
