### PR TITLE
Fix: Declare fields otherwise declared dynamically

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] declares fields otherwise declared dynamically

### CODE REVIEW

**Comment by everton-rosario** [comment]
@localheinz This PR is ok!
Can you please re-visit this (bc of merge conflicts)?
Sorry for the long wait on this.

**Comment by localheinz** [comment]
@everton-rosario 

Resolved!

**Comment by everton-rosario** [comment]
Tks @localheinz !

**Comment by localheinz** [comment]
@everton-rosario 

👍

**Comment by rudyk5** [comment]
This pR

**Comment by rudyk5** [comment]
#88

**Pull request merged**
