### PR TITLE
removed useless folders by using better autloading

### PR DESCRIPTION
**Pull request by OskarStark**
No need for the folders

### CODE REVIEW

**Comment by timjacobi** [comment]
Can you please merge master into this branch?

**Comment by OskarStark** [comment]
done @timjacobi

**Comment by timjacobi** [comment]
@OskarStark the checks are still failing. But actually I think the folder structure is ok like this.

**Comment by OskarStark** [comment]
For the future it would be great if you decide sth like this before I do the rebase stuff...

**Pull request closed without merging**
